In [1]:
import numpy as np
import pandas as pd  # Just for pretty printing of small matrices


# Initial matrix and inverse

In [2]:
# The starter matrix and it's inverse
mat = np.array([[1, 2, 3], [1, 4, 9], [7, 8, 9]])
mat_inv = np.linalg.inv(mat)

# Print key facts
print(f"mat = \n{pd.DataFrame(mat)}")
print(f"Matrix condition number {np.linalg.cond(mat):0.2f}")
print(f"mat_inv = \n{pd.DataFrame(mat_inv)}")


mat = 
   0  1  2
0  1  2  3
1  1  4  9
2  7  8  9
Matrix condition number 99.12
mat_inv = 
          0    1         2
0 -3.000000  0.5  0.500000
1  4.500000 -1.0 -0.500000
2 -1.666667  0.5  0.166667


# Row preconditioning

In [3]:
# Do row preconditioning and invert
precon_row = mat.sum(axis=1)[:, None]  # Array of preconditioner scalars
mat_precon_row = mat / precon_row  # Row preconditioned matrix
check_precon = mat_precon_row.sum(axis=1)
mat_precon_row_inv = np.linalg.inv(
    mat_precon_row
)  # Inverse of row preconditioned matrix
mat_precon_row_inv_norm = (
    mat_precon_row_inv / precon_row.T
)  # Normalize back to unpreconditioned values


# Print results summary
print(f"Row preconditioner: {precon_row.T}")
if np.allclose(check_precon, 1):
    print("Matrix rows preconditioned to 1")
else:
    print("Matrix rows NOT preconditioned to 1")
print(
    f"Row preconditioned matrix condition number {np.linalg.cond(mat_precon_row):0.2f}"
)
print(f"mat_precon_row_inv_norm = \n{pd.DataFrame(mat_precon_row_inv_norm)}")
if np.allclose(mat_inv, mat_precon_row_inv_norm):
    print("Row precoditioned inverse matches direct inverse")
else:
    print("Row precoditioned inverse DOES NOT matches direct inverse")


Row preconditioner: [[ 6 14 24]]
Matrix rows preconditioned to 1
Row preconditioned matrix condition number 45.06
mat_precon_row_inv_norm = 
          0    1         2
0 -3.000000  0.5  0.500000
1  4.500000 -1.0 -0.500000
2 -1.666667  0.5  0.166667
Row precoditioned inverse matches direct inverse


# Column preconditioning

In [4]:
# Do column preconditioning and invert
precon_col = mat.sum(axis=0)[None, :]  # Array of preconditioner scalars
mat_precon_col = mat / precon_col  # Column preconditioned matrix
check_precon = mat_precon_col.sum(axis=0)
mat_precon_col_inv = np.linalg.inv(
    mat_precon_col
)  # Inverse of column preconditioned matrix
mat_precon_col_inv_norm = (
    mat_precon_col_inv / precon_col.T
)  # Normalize back to unpreconditioned values

# Print results summary
print(f"Column preconditioner: {precon_col}")
if np.allclose(check_precon, 1):
    print("Matrix columns preconditioned to 1")
else:
    print("Matrix columns NOT preconditioned to 1")
print(
    f"Column preconditioned matrix condition number {np.linalg.cond(mat_precon_col):0.2f}"
)
print(f"mat_precon_col_inv_norm = \n{pd.DataFrame(mat_precon_col_inv_norm)}")
if np.allclose(mat_inv, mat_precon_col_inv_norm):
    print("Column precoditioned inverse matches direct inverse")
else:
    print("Column precoditioned inverse DOES NOT matches direct inverse")


Column preconditioner: [[ 9 14 21]]
Matrix columns preconditioned to 1
Column preconditioned matrix condition number 92.35
mat_precon_col_inv_norm = 
          0    1         2
0 -3.000000  0.5  0.500000
1  4.500000 -1.0 -0.500000
2 -1.666667  0.5  0.166667
Column precoditioned inverse matches direct inverse
